[workspace]
resolver = "3"
members = [
    "crates/demo",
    "crates/bitbuf",
    "crates/bsp",
    "crates/viewer",
    "crates/vpk",
    "crates/vtf",
    "crates/mdl",
]

[workspace.dependencies]
binrw = "0.15"
glam = "0.30.5"

[profile.dev.package.powerjack-bsp]
opt-level = 3
