[package]
name = "powerjack-ui"
version = "0.0.0"
edition = "2024"

[dependencies]
powerjack-demo = { path = "../demo" }

eframe = { version = "0.33", default-features = false, features = [
    "default_fonts",
    "wgpu",
    "wayland",
    "x11"
] }

wgpu = { version = "27", default-features = false, features = [
    "metal",
    "vulkan",
    "dx12",
] }
egui_extras = { version = "0.33.2", features = ["svg", "file", "image"] }
image = { version = "0.25", features = ["jpeg", "png"] }
chrono = "0.4.42"
rayon = "1.11.0"
tf-demo-parser = "0.6.4"
chroma-dbg = "0.2.1"
opener = "0.8.3"
crossbeam-channel = "0.5.15"

#slint = { version = "1.14.1", default-features = false, features = [
#    "compat-1-2",
#    "backend-default",
#    "renderer-femtovg-wgpu",
#] }
#i-slint-backend-winit = "1.14.1"

#[build-dependencies]
#slint-build = "1.14.1"
