[package]
name = "powerjack-ui"
version = "0.0.0"
edition = "2024"

[dependencies]
powerjack-demo = { path = "../demo" }

iced = { git = "https://github.com/iced-rs/iced", features = ["image"] }
subsecond = "0.7.2"
dioxus-devtools = "0.7.2"

#slint = { version = "1.14.1", default-features = false, features = [
#    "compat-1-2",
#    "backend-default",
#    "renderer-femtovg-wgpu",
#] }
#i-slint-backend-winit = "1.14.1"

#[build-dependencies]
#slint-build = "1.14.1"
