import { Button, VerticalBox, Slider, HorizontalBox } from "std-widgets.slint";
import { ClassPortrait, Class } from "class-portrait.slint";

export enum AttributeKind {
    excellent,
    positive,
    negative
}

export component DemoTile inherits Rectangle {
    in property <image> background_image;
    in property <Class> primary_class;
    in property <string> map_name;
    in property <string> time_played;
    in property <int> num_friends;
    in property <string> kd_ratio;
    in property <string> date;

    in property <[{kind: AttributeKind, text: string}]> attributes;

    VerticalBox {
        spacing: 0;

        Rectangle {
            border-top-left-radius: 24px;
            border-top-right-radius: 24px;

            width: 450px;
            height: 256px;
            background: #222;
            clip: true;

            Image {
                source: background_image;
                width: 450px;
                height: 256px;
                image-fit: contain;

                Rectangle {
                    width: 100%;
                    height: 100%;
                    background: #00000088;

//                    for index in [4, 3, 2, 1, 0] : HorizontalBox {
//                        alignment: start;
//                        x: 128px + index * 36px;
//                        y: 40px;
//                        opacity: 1.0;
//                        TouchArea {
//                            ClassPortrait {
//                                class: medic;
//                                darken: parent.has-hover ? 0.0 : 0.5;
//                                size: 0.5;
//                            }
//                        }
//                    }
                    HorizontalBox {
                        alignment: start;
                        ClassPortrait {
                            class: primary_class;
                        }
                    }

                    VerticalLayout {
                        padding: 18px;
                        spacing: 8px;
                        alignment: start;
                        HorizontalLayout {
                            alignment: end;
                            Text {
                                text: "🕑 " + time_played;
                                font-size: 24px;
                                font-weight: 900;
                                color: white;
                            }
                        }
                        if kd_ratio != "" : HorizontalLayout {
                            alignment: end;
                            Text {
                                text: "🎯 " + kd_ratio;
                                font-size: 16px;
                                font-weight: 900;
                                color: #fff;
                            }
                        }
                        if num_friends != 0 : HorizontalLayout {
                            alignment: end;
                            Text {
                                text: "👥 1 friend";
                                font-size: 16px;
                                font-weight: 900;
                                color: #6f6;
                            }
                        }
                    }

                    VerticalLayout {
                        padding: 12px;
                        padding-right: 16px;
                        spacing: 8px;
                        alignment: end;
                        for attr in attributes: attribute-box := HorizontalLayout {
                            alignment: end;
                            spacing: 4px;

                            icon := Image {
                                source: @image-url("images/icons/angles-down.svg");
                                width: 20px;
                            }
                            label := Text {
                                text: attr.text;
                                font-size: 16px;
                                font-weight: 900;
                                color: #f66;
                            }

                            init => {
                                if (attr.kind == AttributeKind.excellent) {
                                    icon.colorize = #ff6;
                                    icon.source = @image-url("images/icons/star.svg");
                                    label.color = #ff6;
                                } else if (attr.kind == AttributeKind.positive) {
                                    icon.colorize = #6f6;
                                    label.color = #6f6;
                                    icon.source = @image-url("images/icons/angles-up.svg");
                                } else {
                                    icon.colorize = #f66;
                                    label.color = #f66;
                                    icon.source = @image-url("images/icons/angles-down.svg");
                                }
                            }
                        }
                    }
                }

//                VerticalLayout {
//                    alignment: end;
//                    Image {
//                        source: @image-url("images/cohae.jpg");
//                        width: 48px;
//                    }
//                }
            }
        }


        Rectangle {
            border-bottom-left-radius: 16px;
            border-bottom-right-radius: 16px;

            width: 450px;
            height: 48px;
            background: #222;

            HorizontalLayout {
                HorizontalLayout {
                    padding-top: 8px;
                    padding-left: 16px;
                    alignment: start;
                    Text {
                        text: map_name;
                        color: #fff;
                        font-size: 20px;
                    }
                }

                HorizontalBox {
                    padding-top: 14px;
                    padding-right: 12px;
                    alignment: end;
                    Text {
                        text: date;
                        font-italic: true;
                        color: #aaa;
                        font-size: 16px;
                    }
                }
            }
        }
    }
}