[package]
name = "powerjack-demo"
version = "0.0.0"
edition = "2024"

[dependencies]
powerjack-bitbuf = { path = "../bitbuf" }

anyhow = "1.0.60"
bitflags = "2.9.3"
glam.workspace = true

[dev-dependencies]
chroma-dbg = "0.1.2"
